### ISSUE TITLE
Hikar web app stuck on iphone 12

### ISSUE THREAD

**Issue by gitToad** [nickw1/hikar.js#1]
Just leaving some feedback - I tried https://hikar.org/webapp/ on an iphone 12 pro max running ios 14.6

The app gets stuck on the message "Loading data for routing" I am accessing the app from the San Francisco Bay Area, California.

In the debugger I see the following messages:

[Warning] No DPDB device match. (aframe.min.js, line 776)
[Error] Failed to recalculate device parameters.
	(anonymous function) (aframe.min.js:776:19122)
	o (aframe.min.js:775:5265)
	w (aframe.min.js:775:10296)
	(anonymous function) (aframe.min.js:778:19355)
	(anonymous function) (aframe.min.js:778:20830)
	e (aframe.min.js:775:552)
	(anonymous function) (aframe.min.js:995:619)
	o (aframe.min.js:1:636)
	r (aframe.min.js:1:799)
	(anonymous function) (aframe.min.js:1:827)
	(anonymous function) (aframe.min.js:1:318)
	Global Code (aframe.min.js:1:323)
[Warning] Using fallback iOS device measurements. (aframe.min.js, line 776)
[Log] A-Frame Version: 1.0.4 (Date 2020-02-05, Commit #2b359246) (aframe.min.js, line 995)
[Log] three Version (https://github.com/supermedium/three.js): – "^0.111.6" (aframe.min.js, line 995)
[Log] WebVR Polyfill Version: – "^0.10.10" (aframe.min.js, line 995)
[Warning] webvr-polyfill: Invalid timestamps detected: Timestamp from devicemotion outside expected range. (aframe.min.js, line 775)
[Warning] THREE.WebGLRenderer: OES_texture_float_linear extension not supported. (aframe.min.js, line 92)
[Warning] No DPDB device match. (aframe.min.js, line 776)
[Error] Failed to recalculate device parameters.
	(anonymous function) (aframe.min.js:776:19122)
	(anonymous function) (aframe.min.js:775:5487)
[Log] core:a-assets:warn Asset loading timed out in   – 3000 – "ms" (aframe.min.js, line 23)
[Log] Adding data for tile (bundle.js, line 14491, x9)
[Error] Error: Compacted graph contains no forks (topology has no intersections). (bundleworker.js, line 731)

I also looked at the http requests made to the AWS mapzen DEM tiles via the proxy, they are successful.
The requests made to the tsvr.php endpoint for all the initial 9 tiles are:
{
    "features": [],
    "type": "FeatureCollection"
}

Also noticed (and this may be irrelevant to the getting stuck issue) in the debugger network tab that the file
aframe-ar-nft.js
was fetched twice during the app load process.

Anyway, not sure any of this is a bug, perhaps the app was not intended to be used from here. In any case perhaps this feedback is useful.
Happy to do more testing if required.

**Comment by nickw1** [comment]
Hi @gitToad thanks for this. I guess you sent the email to me earlier? If so you'll know that the server doesn't contain the Bay Area (or anywhere else outside of Europe or Turkey) just yet, due to server capacity constraints. *However* thanks for the feedback, I can modify the code so that it behaves more nicely if there is no data.

As I explained in the email, if you would like the Bay Area I can add it in.

Thanks again!

**Comment by gitToad** [comment]
no worries (and thanks for your email), no need to load your server up with more megabytes just for one person. But perhaps you can point the interested public to a rough area lat/lng wise that we could initialize camera coordinates  (simulateLatitude  etc) to see the Hikar demo in our phones ?

**Comment by nickw1** [comment]
OK will do, lat 51.049, lon -0.723 works, though note there appears to be a bug with lat/lon specification in the query string currently - investigating this.

**Comment by nickw1** [comment]
Fixed now. If lat/lon is outside the area covered by the server, it displays 'Loading elevation data' and 'Loading OSM data' without getting stuck on the routing message, and doesn't error in the console. Note: tested on a desktop machine only using a fake lat/lon rather than on-location outside Europe and Turkey.
